name: mmamc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  lottie: ^3.3.3
  shared_preferences: ^2.5.5
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_native_splash: ^2.4.1        # ← ADD
  flutter_local_notifications: ^18.0.1  # ← ADD
  timezone: ^0.9.4                      # ← ADD

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/                    


flutter_native_splash:
  color: "#0F1C3A"
  image: assets/images/logo.png
  android: true
  ios: true